# Generated by Django 3.2 on 2023-03-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='stars',
            new_name='rating',
        ),
    ]
